#!/bin/bash
# mintbootupcommand.sh — installs and runs mintbootup function in Fish

fish
function mintbootup
    while true
        clear
        echo -e "\e[38;5;10m
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXX XXXXX XXXXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX XX XXXXXXXXX
XXXXXXXXXXXXXXXXXXX      XXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXX XXXX  XXXXXXXX X XXXXXXXXXXXXXX  XXXXXXXXX  XXX XXX XXXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX X XXX XXXXXXXX XXX
XXXXXXXXXXXXXXXXXXX XXXXXX XXXX  XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX   XX XXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXX XXX  XXXXXXXXXXX XXXXXXX XXXXXXXXX X XXX XXX XXXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXX  X  XXXXXXXXXXXXXX XXXX XXXXXXXXXX X XX  XXXX XXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXXX   XXXXXXXXXXXXXX XXXXX XXXXXXXXXX  XXX XXXXX XXXXXXX
XXXXXXXXXXXXXXXXXXX XXXXXXX  XXXXXXXXXXXXXX  XXXXX XXXXXXXXXX  XXX XXXXXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  XX XXXXXX XXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX  XXXXXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
XXXXXXXXXXXXXXXXXX      X  XXXXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
XXXXXXXXXXXXXXXX  XXXXXXXXXX  XXXXXXXXXX  XXXXXX    XXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX  XX    XXXXXXXXXXXXX XXXXXXXXXXX
XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX  XX X   XXXXX  XXXXX XXXXXXXXXXX
XXXXXXXXXXXXXXXXX      X  XX XXXXXXXXXXX XXXXXXX   XXX  XXXXX X XXX X XX X    XX
XXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXX XXXXXXXXX     XXXXXX X  XXXX XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXX           XXXXXXXXXXXXXXXXXXXXXXX  X XXXX XXXXXXXXXX
\e[0m"
        echo -e "\e[38;5;10m                         SYSTEM MANAGER\e[0m"
        echo ""
        echo -e "\e[38;5;10m  OPTIONS - 1 (press a) linux version\e[0m"
        echo ""
        echo -e "\e[38;5;10m  Press \e[38;5;11m[a]\e[38;5;10m to run system info\e[0m"
        echo -e "\e[38;5;10m  Press \e[38;5;11m[Ctrl+C]\e[38;5;10m to exit\e[0m"

        set -l key (read --silent --nchars=1)

        if test -z "$key"
            echo -e "\n\e[38;5;10m  ▶ Exiting Mint Client...\e[0m"
            return 0
        end

        switch "$key"
            case a
                echo -e "\e[38;5;10m  ▶ Running system info...\e[0m"
                echo ""
                screenfetch
                echo ""
                echo -e "\e[38;5;10m  Press any key to return to the menu...\e[0m"
                read --silent --nchars=1
            case "*"
                echo -e "\e[38;5;9m  Invalid key. Press \e[38;5;11m[a]\e[38;5;9m or \e[38;5;11m[Ctrl+C]\e[38;5;9m.\e[0m"
                sleep 1
        end
    end
end

funcsave mintbootup
